alert("Hello, World! I am an alert box!");
<!DOCTYPE html>
<html>
<body>
    <button onclick="My_First_Function ()">
        Click me!
    </button>
    <script>
        function My_First_function ()  {
            var String = "Kiss me, I'm Irish!";
            var result = String.fontcolor("green");
            document.getElementById("Irish") .innerHTML = result;

        }
        </script>
        </body>
        </html>